
2019-08-17 15:24:38 ERROR [2036-Thread-1] LogMiddleware.process_exception line 11: 'QuerySet' object has no attribute 'to_dict'
2019-08-17 15:24:54 ERROR [9296-Thread-1] LogMiddleware.process_exception line 11: Object of type 'QuerySet' is not JSON serializable
2019-08-17 15:25:07 ERROR [9492-Thread-1] LogMiddleware.process_exception line 11: Object of type 'method' is not JSON serializable
2019-08-17 15:29:18 ERROR [7440-Thread-1] LogMiddleware.process_exception line 11: 'QuerySet' object has no attribute 'value'
2019-08-17 15:29:20 ERROR [7440-Thread-1] LogMiddleware.process_exception line 11: 'QuerySet' object has no attribute 'value'
2019-08-17 15:29:26 ERROR [7440-Thread-1] LogMiddleware.process_exception line 11: 'QuerySet' object has no attribute 'value'
2019-08-17 15:38:12 ERROR [2592-Thread-1] LogMiddleware.process_exception line 11: 'bool' object is not iterable
2019-08-17 15:40:59 ERROR [11952-Thread-1] LogMiddleware.process_exception line 11: Object of type 'QuerySet' is not JSON serializable
2019-08-17 16:30:22 ERROR [11476-Thread-1] LogMiddleware.process_exception line 11: 'QuerySet' object has no attribute 'value'
2019-08-17 16:30:26 ERROR [11468-Thread-1] LogMiddleware.process_exception line 11: 'QuerySet' object has no attribute 'value'
2019-08-17 16:30:39 ERROR [10604-Thread-1] LogMiddleware.process_exception line 11: 'QuerySet' object has no attribute 'value'
2019-08-17 16:31:09 ERROR [13172-Thread-1] LogMiddleware.process_exception line 11: 
2019-08-17 17:23:06 ERROR [12132-Thread-1] LogMiddleware.process_exception line 11: Cannot resolve keyword 'user' into field. Choices are: date, id, likemural, path, type, type_id
2019-08-17 17:23:56 ERROR [12808-Thread-1] LogMiddleware.process_exception line 11: Cannot resolve keyword 'user' into field. Choices are: date, id, likemural, path, type, type_id
2019-08-17 19:01:18 ERROR [11620-Thread-1] LogMiddleware.process_exception line 11: 'int' object is not iterable
2019-08-17 19:06:18 ERROR [13268-Thread-1] LogMiddleware.process_exception line 11: 'type_id'
2019-08-17 20:40:31 ERROR [5188-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object has no attribute 'exists'
=======
2019-08-17 15:35:29 ERROR [6884-Thread-1] LogMiddleware.process_exception line 11: get() takes 1 positional argument but 2 were given
2019-08-17 15:36:14 ERROR [11556-Thread-1] LogMiddleware.process_exception line 11: In order to allow non-dict objects to be serialized set the safe parameter to False.
2019-08-17 15:38:16 ERROR [10804-Thread-1] LogMiddleware.process_exception line 11: get() takes 1 positional argument but 2 were given
2019-08-17 15:38:28 ERROR [10980-Thread-1] LogMiddleware.process_exception line 11: In order to allow non-dict objects to be serialized set the safe parameter to False.
2019-08-17 16:09:32 ERROR [11372-Thread-1] LogMiddleware.process_exception line 11: check_password() missing 1 required positional argument: 'encoded'
2019-08-17 16:09:34 ERROR [11372-Thread-1] LogMiddleware.process_exception line 11: check_password() missing 1 required positional argument: 'encoded'
2019-08-17 17:14:11 ERROR [12416-Thread-1] LogMiddleware.process_exception line 11: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2019-08-17 17:14:57 ERROR [6256-Thread-1] LogMiddleware.process_exception line 11: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2019-08-17 17:16:51 ERROR [12392-Thread-1] LogMiddleware.process_exception line 11: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
2019-08-17 17:17:28 ERROR [10668-Thread-1] LogMiddleware.process_exception line 11: 'str' object has no attribute 'as_string'
2019-08-17 17:34:47 ERROR [10576-Thread-1] LogMiddleware.process_exception line 11: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)
2019-08-17 17:35:46 ERROR [13168-Thread-1] LogMiddleware.process_exception line 11: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)
2019-08-17 17:37:07 ERROR [13032-Thread-1] LogMiddleware.process_exception line 11: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)
2019-08-17 17:41:58 ERROR [13076-Thread-1] LogMiddleware.process_exception line 11: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)
2019-08-17 17:42:21 ERROR [10576-Thread-1] LogMiddleware.process_exception line 11: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)
2019-08-17 17:44:34 ERROR [13096-Thread-1] LogMiddleware.process_exception line 11: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)
2019-08-17 17:45:34 ERROR [4108-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object is not iterable
2019-08-17 17:46:51 ERROR [5184-Thread-1] LogMiddleware.process_exception line 11: 'str' object has no attribute 'as_string'
2019-08-17 17:53:25 ERROR [4784-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object is not callable
2019-08-17 17:54:23 ERROR [9768-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object is not callable
2019-08-17 17:55:07 ERROR [9472-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object is not callable
2019-08-17 17:56:20 ERROR [12452-Thread-1] LogMiddleware.process_exception line 11: (535, b'Error: \xc7\xeb\xca\xb9\xd3\xc3\xca\xda\xc8\xa8\xc2\xeb\xb5\xc7\xc2\xbc\xa1\xa3\xcf\xea\xc7\xe9\xc7\xeb\xbf\xb4: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
2019-08-17 17:57:41 ERROR [9848-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object is not iterable
2019-08-17 18:00:03 ERROR [3164-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object is not iterable
2019-08-17 18:06:14 ERROR [11016-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object is not iterable
2019-08-17 18:06:42 ERROR [12944-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object is not iterable
2019-08-17 18:07:16 ERROR [10668-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object is not iterable
2019-08-17 20:29:23 ERROR [10492-Thread-1] LogMiddleware.process_exception line 11: 'WSGIRequest' object has no attribute 'FILED'
2019-08-17 20:29:32 ERROR [10492-Thread-1] LogMiddleware.process_exception line 11: 'WSGIRequest' object has no attribute 'FILED'
2019-08-17 20:30:00 ERROR [4880-Thread-1] LogMiddleware.process_exception line 11: 'WSGIRequest' object has no attribute 'FEILD'
2019-08-17 20:30:20 ERROR [10144-Thread-1] LogMiddleware.process_exception line 11: 'WSGIRequest' object has no attribute 'FILE'
2019-08-17 20:32:24 ERROR [9384-Thread-1] LogMiddleware.process_exception line 11: 'WSGIRequest' object has no attribute 'FILED'
2019-08-17 20:33:29 ERROR [10368-Thread-1] LogMiddleware.process_exception line 11: 'WSGIRequest' object has no attribute 'cache'
2019-08-17 20:39:51 ERROR [6984-Thread-1] LogMiddleware.process_exception line 11: first() got an unexpected keyword argument 'id'
2019-08-17 20:41:07 ERROR [11120-Thread-1] LogMiddleware.process_exception line 11: invalid literal for int() with base 10: 'nan'
2019-08-17 20:56:17 ERROR [9696-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object has no attribute 'sex'
2019-08-17 21:06:03 ERROR [4828-Thread-1] LogMiddleware.process_exception line 11: Object of type User is not JSON serializable

<<<<<<< HEAD
<<<<<<< HEAD
2019-08-18 09:12:11 ERROR [6932-Thread-3] LogMiddleware.process_exception line 11: Mural matching query does not exist.
2019-08-18 09:13:36 ERROR [11144-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object has no attribute 'type_id'
2019-08-18 09:15:45 ERROR [7028-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object has no attribute 'to_dict'
2019-08-18 09:40:50 ERROR [1492-Thread-1] LogMiddleware.process_exception line 11: too many values to unpack (expected 2)
2019-08-18 10:00:22 ERROR [1272-Thread-1] LogMiddleware.process_exception line 11: Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x0000000004351908>>": "UserImg.user" must be a "User" instance.
2019-08-18 10:14:38 ERROR [5656-Thread-1] LogMiddleware.process_exception line 11: Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x00000000049CDA20>>": "UserImg.user" must be a "User" instance.
2019-08-18 10:19:40 ERROR [11988-Thread-1] LogMiddleware.process_exception line 11: 'WSGIRequest' object has no attribute 'cache'
=======
2019-08-18 10:17:57 ERROR [6388-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object has no attribute 'name'
<<<<<<< HEAD
>>>>>>> dd8529578dc390bb5d9610686fe26d5d2568c30e
<<<<<<< HEAD
=======
2019-08-18 13:02:04 ERROR [2712-Thread-1] LogMiddleware.process_exception line 11: Object of type QuerySet is not JSON serializable
2019-08-18 13:45:22 ERROR [11204-Thread-1] LogMiddleware.process_exception line 11: 'WSGIRequest' object has no attribute 'get'
2019-08-18 13:45:42 ERROR [11044-Thread-1] LogMiddleware.process_exception line 11: unsupported operand type(s) for +: 'QuerySet' and 'QuerySet'
2019-08-18 13:46:43 ERROR [11168-Thread-1] LogMiddleware.process_exception line 11: unsupported operand type(s) for +: 'QuerySet' and 'QuerySet'
2019-08-18 13:47:02 ERROR [7472-Thread-1] LogMiddleware.process_exception line 11: unsupported operand type(s) for +: 'QuerySet' and 'QuerySet'
2019-08-18 13:47:23 ERROR [624-Thread-1] LogMiddleware.process_exception line 11: unsupported operand type(s) for +: 'QuerySet' and 'QuerySet'
2019-08-18 13:58:31 ERROR [5740-Thread-1] LogMiddleware.process_exception line 11: 
2019-08-18 15:10:40 ERROR [11204-Thread-1] LogMiddleware.process_exception line 11: 'User' object has no attribute 'values'
2019-08-18 15:11:10 ERROR [2232-Thread-1] LogMiddleware.process_exception line 11: 'User' object has no attribute 'value'
2019-08-18 15:11:37 ERROR [10564-Thread-1] LogMiddleware.process_exception line 11: 'User' object has no attribute 'values'
2019-08-18 15:20:30 ERROR [10600-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object has no attribute 'exists'
2019-08-18 15:34:21 ERROR [10996-Thread-1] LogMiddleware.process_exception line 11: Object of type QuerySet is not JSON serializable
2019-08-18 15:44:22 ERROR [11200-Thread-1] LogMiddleware.process_exception line 11: Object of type QuerySet is not JSON serializable
2019-08-18 16:04:25 ERROR [8532-Thread-1] LogMiddleware.process_exception line 11: unhashable type: 'dict'
2019-08-18 16:05:02 ERROR [10132-Thread-1] LogMiddleware.process_exception line 11: 'QuerySet' object has no attribute 'name'
2019-08-18 16:05:26 ERROR [9484-Thread-1] LogMiddleware.process_exception line 11: unhashable type: 'dict'
2019-08-18 16:06:40 ERROR [10132-Thread-1] LogMiddleware.process_exception line 11: 'int' object has no attribute 'type'
2019-08-18 16:07:25 ERROR [9028-Thread-1] LogMiddleware.process_exception line 11: 'int' object has no attribute 'type'
2019-08-18 16:08:32 ERROR [7396-Thread-1] LogMiddleware.process_exception line 11: 'int' object has no attribute 'type'
2019-08-18 16:09:11 ERROR [696-Thread-1] LogMiddleware.process_exception line 11: 'int' object has no attribute 'type'
2019-08-18 16:10:35 ERROR [10568-Thread-1] LogMiddleware.process_exception line 11: unhashable type: 'dict'
2019-08-18 16:12:26 ERROR [10860-Thread-1] LogMiddleware.process_exception line 11: unhashable type: 'dict'
2019-08-18 16:13:20 ERROR [9168-Thread-1] LogMiddleware.process_exception line 11: unhashable type: 'dict'
2019-08-18 16:13:41 ERROR [11088-Thread-1] LogMiddleware.process_exception line 11: unhashable type: 'dict'
2019-08-18 16:14:19 ERROR [6900-Thread-1] LogMiddleware.process_exception line 11: unhashable type: 'dict'
>>>>>>> lyf
=======
2019-08-18 11:53:33 ERROR [12284-Thread-1] LogMiddleware.process_exception line 11: Cannot assign "<QuerySet [<User: User object (5)>]>": "UserImg.user" must be a "User" instance.
2019-08-18 12:02:58 ERROR [1864-Thread-1] LogMiddleware.process_exception line 11: Cannot resolve keyword 'user_id' into field. Choices are: date, fans, fans_id, followers, followers_id, id
2019-08-18 14:38:01 ERROR [11308-Thread-1] LogMiddleware.process_exception line 11: 'dict' object has no attribute 'delete'
2019-08-18 14:40:18 ERROR [11160-Thread-1] LogMiddleware.process_exception line 11: 'UserImg' object has no attribute 'values'
2019-08-18 15:51:48 ERROR [12616-Thread-1] LogMiddleware.process_exception line 11: Cannot resolve keyword 'id_delete' into field. Choices are: del_date, id, info, is_delete, path, type, upload_date, user, user_id
2019-08-18 16:12:11 ERROR [2664-Thread-1] LogMiddleware.process_exception line 11: ['’‘ 必须为合法的日期格式，请使用 YYYY-MM-DD 格式。']
2019-08-18 16:13:31 ERROR [12880-Thread-1] LogMiddleware.process_exception line 11: (2003, "Can't connect to MySQL server on '111.230.10.23' (10060)")
>>>>>>> slj
=======
2019-08-18 11:36:37 ERROR [13944-Thread-1] LogMiddleware.process_exception line 11: 'AnonymousUser' object is not iterable
2019-08-18 11:37:48 ERROR [10204-Thread-1] LogMiddleware.process_exception line 11: 'AnonymousUser' object is not iterable
2019-08-18 11:38:25 ERROR [17116-Thread-1] LogMiddleware.process_exception line 11: name 'curr_user' is not defined
2019-08-18 11:38:43 ERROR [7760-Thread-1] LogMiddleware.process_exception line 11: 'AnonymousUser' object is not iterable
2019-08-18 11:39:35 ERROR [10556-Thread-1] LogMiddleware.process_exception line 11: 'AnonymousUser' object is not iterable
2019-08-18 11:41:32 ERROR [10844-Thread-1] LogMiddleware.process_exception line 11: 'AnonymousUser' object is not iterable
2019-08-18 11:42:27 ERROR [12932-Thread-1] LogMiddleware.process_exception line 11: 'AnonymousUser' object is not iterable
2019-08-18 12:29:20 ERROR [11776-Thread-1] LogMiddleware.process_exception line 11: 'WSGIRequest' object has no attribute 'peoele'
2019-08-18 13:29:10 ERROR [9724-Thread-1] LogMiddleware.process_exception line 11: must be str, not type
2019-08-18 13:30:11 ERROR [8512-Thread-1] LogMiddleware.process_exception line 11: unsupported operand type(s) for +: 'InMemoryUploadedFile' and 'str'
>>>>>>> pqw
<<<<<<< HEAD
2019-08-19 10:16:53 ERROR [11216-Thread-1] LogMiddleware.process_exception line 11: 'WSGIRequest' object has no attribute 'FILE'
<<<<<<< HEAD
=======
2019-08-19 12:51:53 ERROR [12440-Thread-1] LogMiddleware.process_exception line 11: 'NoneType' object has no attribute 'path'
<<<<<<< HEAD
>>>>>>> slj
=======
2019-08-19 15:24:59 ERROR [12160-Thread-1] LogMiddleware.process_exception line 11: 'QuerySet' object has no attribute 'id'
>>>>>>> slj
=======
2019-08-20 16:34:13 ERROR [10344-Thread-1] LogMiddleware.process_exception line 11: Connection unexpectedly closed
2019-08-20 16:35:15 ERROR [10824-Thread-1] LogMiddleware.process_exception line 11: Connection unexpectedly closed
2019-08-20 16:36:12 ERROR [7876-Thread-1] LogMiddleware.process_exception line 11: Connection unexpectedly closed
2019-08-20 16:36:57 ERROR [5956-Thread-1] LogMiddleware.process_exception line 11: Connection unexpectedly closed
2019-08-20 16:37:53 ERROR [7908-Thread-1] LogMiddleware.process_exception line 11: Connection unexpectedly closed
2019-08-20 16:41:29 ERROR [9752-Thread-1] LogMiddleware.process_exception line 11: Connection unexpectedly closed
2019-08-20 16:44:57 ERROR [9284-Thread-1] LogMiddleware.process_exception line 11: Connection unexpectedly closed
>>>>>>> lyf
